name: "Publish Release"

on:
  push:
    branches:
      - main 

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: npm install

      - name: build frontend
        run: npm run build

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }} #crea el tag automáticamente
          releaseName: "App ${{ github.ref_name }}"
          includeUpdaterJson: true
          releaseBody: "- Nuevo diseño de navegación: barra superior (header) con acceso rápido al perfil\n- Perfil de usuario ahora se abre en ventana modal directamente desde el header\n- Interfaz más limpia y consistente en todas las pantallas\n- Navegación entre secciones más fluida y respuesta inmediata\n- Múltiples mejoras visuales y corrección de errores reportados\n- Optimizaciones de rendimiento para una experiencia más fluida\n- Implementación de componente de reloj dinámico en el encabezado global "
          releaseDraft: false
          prerelease: false