name: "Publish Release"

on:
  push:
    branches:
      - main 

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: npm install

      - name: build frontend
        run: npm run build

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__ #crea el tag automáticamente
          releaseName: "App v__VERSION__"
          includeUpdaterJson: true
          releaseBody: "- Abonos múltiples y variables por venta: registra pagos en partes con control de total cobrado y saldo pendiente\n- Acordeón de reportes rediseñado con mejor jerarquía visual, espaciado optimizado y separación más clara de la información\n- Visualización mejorada de productos en el detalle expandido de reportes\n- La gestión de abonos ahora se centraliza en el modal de edición de venta para una interfaz más limpia\n- Correcciones en modales y botones: mejor comportamiento del selector de productos con mucho inventario y ajustes de visibilidad en el botón de detalles\n- Mejoras generales de estabilidad y consistencia visual en la aplicación"
          releaseDraft: false
          prerelease: false
